# Generated by Django 4.2.7 on 2023-11-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_members_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Province',
        ),
        migrations.RemoveField(
            model_name='member',
            name='city',
        ),
        migrations.RemoveField(
            model_name='member',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='member',
            name='institution',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='payment_method',
            field=models.CharField(default='', max_length=40),
        ),
    ]
