# Generated by Django 4.2.7 on 2023-11-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_member_province_remove_member_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
    ]
