# Generated by Django 4.2.7 on 2023-11-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_member_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='committee',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(default='Member', max_length=30),
        ),
    ]
